language: node_js

node_js: node

install:
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false

# Pull requests are built by default.
branches:
  only:
  - master
